[package]
name = "fxsm"
version = "0.2.0"
authors = ["Victor Polevoy <fx@thefx.co>"]

description = "A state machine procedural macro for enums."
license = "MIT"
keywords = ["state", "machine"]

repository = "https://github.com/iddm/fxsm"
